//------------crear------------
###
POST http://localhost:9000/api/users
Content-Type: application/json

{      
    "nombre": "isai",
    "nombreUsers": "user2",
    "contraseña": "1234User2",
    "correo": "isai@gmail.comm",
    "pregunta": "como se llama tu perro",
    "respuesta": "suri"
}

//------------Mostrar------------
###
GET http://localhost:9000/api/users

//------------Buscar------------
###
GET http://localhost:9000/api/users/64dc509bd2ac045daa786946




//------------Actualizar------------
###
PUT http://localhost:9000/api/users/64dc509bd2ac045daa786946
Content-Type: application/json

{
    "nombre": "user",
    "nombreUsers": "user",
    "contraseña": "1234User",
    "correo": "user2@gmail.com",
    "pregunta": "como se llama tu perrooo",
    "respuesta": "surisss",
    "rol":"64dc4875a909109c337b700e"
}



//------------Eliminar------------
###
DELETE http://localhost:9000/api/users/64dc509bd2ac045daa786946

//_____________________ Productos ___________________________________________________________

//------------crear------------
###
POST http://localhost:9000/api/productos
Content-Type: application/json

{
    "nombre":"uvas",
    "descripcion":"64e7f89f05d3e52dbf9465d0",
    "imagen":"asffvjhidufg",
    "precio":"23",
    "sabor":"fresa",
    "presentacion":"caja",
    "existencia":"31"
}



//------------Mostrar------------
###
GET http://localhost:9000/api/productos




//------------Buscar------------
###
GET http://localhost:9000/api/productos/6489f3541ed47f91a30b39ff




//------------Actualizar------------
###
PUT http://localhost:9000/api/productos/6489f3541ed47f91a30b39ff
Content-Type: application/json

{
    "nombre":"uvas",
    "descripcion":"fresa fresca",
    "imagen":"asffvjhidufg.png",
    "precio":"23",
    "sabor":"fresa",
    "presentacion":"caja",
    "existencia":"31"
}



//------------Eliminar------------
###
DELETE http://localhost:9000/api/productos/64e7f9b42a586cc9b4041708


//_______________________________ redesSociales ____________________________________________________________

//------------crear------------
###
POST http://localhost:9000/api/redesEmpresa
Content-Type: application/json

{
    "tipo":"Whatsapp",
    "enlace":"https://web.whatsapp.com"
}



//------------Mostrar------------
###
GET http://localhost:9000/api/redesEmpresa




//------------Buscar------------
###
GET http://localhost:9000/api/redesEmpresa/6489f7b81ed47f91a30b3a09




//------------Actualizar------------
###
PUT http://localhost:9000/api/redesEmpresa/6489f7b81ed47f91a30b3a09
Content-Type: application/json

{
    "tipo":"Whatsapp",
    "enlace":"https://web.whatsapp.coms"
}



//------------Eliminar------------
###
DELETE http://localhost:9000/api/redesEmpresa/6489f7b81ed47f91a30b3a09


//__________________________________informacion de la empresa_______________________________________________________________

//------------crear------------
###
POST http://localhost:9000/api/infEmpre
Content-Type: application/json

{
    "nombre":"NombreEmpresa",
    "informacion":"esta empresa de dedica a mostrar productos de venta",
    "direccion":"col.ejemplo S/N",
    "telefono":"1234567890",
    "correo":"ejemplo2023@gmail.com",
    "logo":"dfbashfguea.png"
}



//------------Mostrar------------
###
GET http://localhost:8000/api/infEmpre




//------------Buscar------------
###
GET http://localhost:9000/api/infEmpre/6489f8f81ed47f91a30b3a12




//------------Actualizar------------
###
PUT http://localhost:9000/api/infEmpre/6489f8f81ed47f91a30b3a12
Content-Type: application/json

{
    "nombre":"NombreEmpresas",
    "informacion":"esta empresa de dedica a mostrar productos de venta",
    "direccion":"col.ejemplo S/N",
    "telefono":"1234567890",
    "correo":"ejemplo2023@gmail.com",
    "logo":"dfbashfguea.png"
}



//------------Eliminar------------
###
DELETE http://localhost:9000/api/infEmpre/6489f8f81ed47f91a30b3a12


//_________________________________________Roles de ususario___________________________________________________
//------------crear------------
###
POST http://localhost:9000/api/rol
Content-Type: application/json

{
    "rol":"user",
    "descripcion":"Usuario"
}



//------------Mostrar------------
###
GET http://localhost:9000/api/rol




//------------Buscar------------
###
GET http://localhost:9000/api/rol/6489e9e61ed47f91a30b39e7




//------------Actualizar------------
###
PUT http://localhost:9000/api/rol/6489e9e61ed47f91a30b39e7
Content-Type: application/json

{
    "rol":"user",
    "descripcion":"Usuario"
}



//------------Eliminar------------
###
DELETE http://localhost:9000/api/rol/6489e9e61ed47f91a30b39e7





//_________________________________________ Slider ___________________________________________________
//------------crear------------
###
POST http://localhost:8000/api/slider
Content-Type: application/json

{
    "titulo":"inicios",
    "descripcion":"descripcion de productos",
    "imagen":"adhbdfikewg"
}



//------------Mostrar------------
###
GET http://localhost:8000/api/slider




//------------Buscar------------
###
GET http://localhost:8000/api/slider/6490b20f7382740d8eb6ab41




//------------Actualizar------------
###
PUT http://localhost:8000/api/slider/6490b20f7382740d8eb6ab41
Content-Type: application/json

{
    "titulo":"inicios",
    "descripcion":"descripcion de productos 2",
    "imagen":"adhbdfikewg"
}



//------------Eliminar------------
###
DELETE http://localhost:9000/api/slider

//_________________________________________ Categoria ___________________________________________________
//------------crear------------
###
POST http://localhost:9000/api/categoria
Content-Type: application/json

{
    "nombre":"Lacteos"
}



//------------Mostrar------------
###
GET http://localhost:9000/api/categoria




//------------Buscar------------
###
GET http://localhost:9000/api/categoria/64e7f88e05d3e52dbf9465ce




//------------Actualizar------------
###
PUT http://localhost:9000/api/categoria/64e7f88e05d3e52dbf9465ce
Content-Type: application/json

{
    "nombre":"Jugos"
}



//------------Eliminar------------
###
DELETE http://localhost:9000/api/categoria/64e7f89f05d3e52dbf9465d0

